name: venv_website
channels:
  - defaults
dependencies:
  - asgiref=3.5.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.1
  - backports.zoneinfo=0.2.1
  - brotlipy=0.7.0
  - ca-certificates=2024.12.31
  - certifi=2022.9.24
  - cffi=1.15.1
  - colorama=0.4.5
  - cryptography=38.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - django=4.1
  - entrypoints=0.4
  - executing=0.8.3
  - freetype=2.12.1
  - idna=3.4
  - ipykernel=6.15.2
  - ipython=8.6.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.4.7
  - jupyter_core=4.11.2
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.5
  - openssl=1.1.1w
  - packaging=21.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pywin32=302
  - pyzmq=23.2.0
  - selenium=3.141.0
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - sqlparse=0.4.3
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - urllib3=1.26.12
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - attrs==23.2.0
    - charset-normalizer==2.1.1
    - exceptiongroup==1.2.1
    - gunicorn==23.0.0
    - h11==0.14.0
    - numpy==1.24.4
    - outcome==1.3.0.post0
    - pandas==2.0.3
    - python-dotenv==0.21.0
    - pytz==2024.1
    - requests==2.28.1
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - tqdm==4.64.1
    - trio==0.25.1
    - trio-websocket==0.11.1
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - webdriver-manager==4.0.1
    - websocket-client==1.8.0
    - wsproto==1.2.0
